name: Build and Deploy to Google Play

on:
  workflow_dispatch:
  push:
    branches:
      - pitam

jobs:
  build:
    env:
      STORE_PASS_ANDROID: ${{ secrets.STORE_PASS_ANDROID }}
      KEY_PASS_ANDROID: ${{ secrets.KEY_PASS_ANDROID }}
      SERVICE_ACCOUNT_ANDROID: ${{ secrets.SERVICE_ACCOUNT_ANDROID }}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Add Android platform
        run: ionic cordova platform add android

      - name: Cordova Build
        run: ionic cordova build android --prod --release

      - name: Sign App Bundle
        working-directory: .
        run: jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore biblecommentary.keystore -storepass $STORE_PASS_ANDROID -keypass $KEY_PASS_ANDROID platforms/android/app/build/outputs/bundle/release/app-release.aab biblecommentary 

      - name: Install zipalign
        run: sudo apt install -y zipalign

      - name: zipalign App Bundle
        working-directory: ./platforms/android/
        run: zipalign -v 4 app/build/outputs/bundle/release/app-release.aab app/build/outputs/bundle/release/final.aab 

      - name: Upload release bundle
        uses: actions/upload-artifact@v1
        with:
          name: upload-release
          path: platforms/android/app/build/outputs/bundle/release/final.aab

      - name: Install python dependencies
        run: pip install oauth2client && pip install google-api-python-client

      - name: Publish App Bundle
        working-directory: .
        run: python publish_to_google_play.py com.bible.studycommentary platforms/android/app/build/outputs/bundle/release/final.aab