name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
              
      - name: Download Provisioning Profiles
        id: provisioning-profiles
        uses: apple-actions/download-provisioning-profiles@v1
        with: 
          bundle-id: 'com.ionicframework.biblecommentary'
          profile-type: 'IOS_APP_STORE'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
    
      - name: List provisioning profiles
        run: echo ${{ steps.provisioning-profiles.outputs.profiles }}

      - name: Import code signing certificate
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install -g ionic
          npm install --force

      - name: Build artifact
        run: ionic cordova build ios --device --developmentTeam="Moshe Cohen"
